### PR TITLE
Clarify that a relative URL is supported in subresource loading

### LINKED ISSUE #656: Support relative URLs in resources= attribute in <link>-based API.
Regarding [`<link>`-based API](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md#link-based-api), we might want to support relative URLs in `resources=` attribute.

e.g.
`https://example.com/index.html` can have a link element as follows:
``` html
<link
  rel="webbundle"
  href="https://example.com/dir/subresources.wbn"
  resources="dir/a.js dir/b.js dir/c.png"
/>
```

instead of the example in the explainer:
``` html
<link
  rel="webbundle"
  href="https://example.com/dir/subresources.wbn"
  resources="https://example.com/dir/a.js https://example.com/dir/b.js https://example.com/dir/c.png"
/>
```

Note that a relative URL will be resolved on the *page*'s base URL, instead of a bundle's URL.

### PR DESCRIPTION
**Pull request by hayatoito**
Fixes #656.

### CODE REVIEW

**Comment by hayatoito** [comment]
@irori @horo-t 
Could you take a look?
Before we support a relative URL in chromium, it would be better to update the explainer.

**Review by irori — APPROVED** [review]
lgtm

**Review by horo-t — APPROVED** [review]
lgtm

**Comment by hayatoito** [comment]
It seems continuous-integration/travis-ci doesn't finish, and I can't find any link where I can investigate what's going on.
Is there any good way to triage?

**Comment by irori** [comment]
https://travis-ci.org/github/WICG/webpackage/builds/ says

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Pull request merged**
