### PR TITLE
Use the signature context string to distinguish draft versions.

### PR DESCRIPTION
**Pull request by jyasskin**
Thanks @sleevi for noticing the problem.

[Preview](https://jyasskin.github.io/webpackage/include-version-in-sig-context/draft-yasskin-http-origin-signed-responses.html), [Diff](https://tools.ietf.org/rfcdiff?url1=https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.txt&url2=https://jyasskin.github.io/webpackage/include-version-in-sig-context/draft-yasskin-http-origin-signed-responses.txt)

### CODE REVIEW

**Comment by sleevi** [comment]
Happy to explain. This is about mitigation version rollback attacks. Right now, the version of the envelope is outside of the signed data. This creates the opportunity for an attacker to alter the version number, causing the signed data to be interpreted differently.

In Chromium, it came up in exploring the b0 to b1 transition, in which b0 ignores the OCSP response, but b1 requires it. An attacker could take a signed b1 response, mark it as b0, and bypass those security checks.

Similar to how X.509 certificates include the signature algorithm within the inner (signed) context, in addition to the outer envelope, or how TLS includes the version number as part of the session transcript, the goal is to ensure that the externally-negotiated properties (such as version) are also bound within the internal, signed content, to prevent any confusion issues. These are functionally the same as cross-protocol attacks, it just happens that its different versions of the same protocol (but functionally different protocols).

The general method of mitigating these cross-protocol attacks is using the context string, to ensure that distinct signatures are created for distinct protocols. This change is necessary, but I'm not entirely sure it's sufficient - if the Web Packaging protocol evolves over time / additional versions, the context string of those subsequent versions will still need to migrate.

Thus, it may make sense to explicitly include both versioning and draft numbers, of which the latter is more applicable here, and formalize that as an inherent part of the protocol. That's the sufficient part :)

**Comment by davidben** [comment]
> I'm curious about the motivation

All signature payloads with the same key be distinguishable, otherwise an attacker can cause the verifier to misinterpret a signature made in one protocol as something else in a different protocol. This includes differences between different versions of the same protocol.

As a toy example, consider if one version signed request headers followed by response headers, and then another version switched the order. Without baking the version into the signature, I can trick the receiver into accepting a signed exchange different from what the origin actually signed.

**Comment by sleevi** [comment]
@jyasskin That sounds good, as it makes sure the expectation is setup in the base spec and so we remember to rev on any semantically-relevant change (overall) and on drafts :)

**Comment by jyasskin** [comment]
Done.

**Comment by twifkak** [comment]
Thanks for the explanations!

**Comment by nyaxt** [comment]
Would you add a ChangeLog entry too?

**Comment by jyasskin** [comment]
> Would you add a ChangeLog entry too? — @nyaxt 

Whoops, thanks, done.

**Pull request merged**
