### PR TITLE
Add go.mod/go.sum

### PR DESCRIPTION
**Pull request by hajimehoshi**
Add `go.mod` and `go.sum` so that the dependent library versions are specified explicitly. This affects Go 1.11 module usages (without $GOPATH), and should not affect the current usual usage (with $GOPATH).

This is a preparation for Go modules which will be officially introduced at Go 1.12.

Note: you can test this by:

1. Checking out https://github.com/WICG/webpackage at your local machine, not under `$GOPATH/src`
2. Run `GO111MODULE=on go test ./...`

### CODE REVIEW

**Comment by hajimehoshi** [comment]
I found some tests in bundle failed:

```
$ GO111MODULE=on go test ./...
# github.com/WICG/webpackage/go/bundle
go/bundle/bundle.go:91: Fprintf format %s has arg e.Response.Status of wrong type int
# github.com/WICG/webpackage/go/bundle/cmd/gen-bundle
go/bundle/cmd/gen-bundle/fromdir.go:90: Errorf call needs 1 arg but has 2 args
ok      github.com/WICG/webpackage/go/signedexchange    (cached)
ok      github.com/WICG/webpackage/go/signedexchange/cbor       (cached)
ok      github.com/WICG/webpackage/go/signedexchange/certurl    (cached)
ok      github.com/WICG/webpackage/go/signedexchange/internal/bigendian (cached)
ok      github.com/WICG/webpackage/go/signedexchange/mice       (cached)
ok      github.com/WICG/webpackage/go/webpack   (cached)
ok      github.com/WICG/webpackage/go/webpack/cbor      (cached)
```

Is this no longer maintained?

**Comment by hajimehoshi** [comment]
Then would it be better to remove bundle?

**Comment by nyaxt** [comment]
Would you update this PR?

**Comment by hajimehoshi** [comment]
```
go: github.com/Sirupsen/logrus@v1.3.0: parsing go.mod: unexpected module path "github.com/sirupsen/logrus" 
```

Looks like there are an unavailable package. I'll take a look.

**Comment by nyaxt** [comment]
Let's wait for the hargo PR merge

**Comment by nyaxt** [comment]
@hajimehoshi now the pr is merged, would you update this pr?

**Pull request merged**
