### PR TITLE
Mark that we're intentionally on CT v1.

### PR DESCRIPTION
**Pull request by jyasskin**
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/webpackage/pull/712.html" title="Last updated on Feb 17, 2022, 11:38 PM UTC (0012db8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webpackage/712/826b22e...jyasskin:0012db8.html" title="Last updated on Feb 17, 2022, 11:38 PM UTC (0012db8)">Diff</a>

### CODE REVIEW

**Comment by hayatoito** [comment]
Can we have a reviewer for this?
@irori is appropriate?

If this is a minor update for SXG and don't need any intense review, I am happy to do a rubber-stamp.

**Comment by jyasskin** [comment]
This is primarily to fix the build, but it's not the obvious fix after one RFC obsoletes another. I checked with Chrome Security, and it sounds like we don't have a plan to move to v2, so signed exchanges shouldn't either.

**Comment by jyasskin** [comment]
It's *part* of #704: I think the bikeshed bit of the action that's failing there is unnecessary, but I can't be sure while this action is failing.

**Review by irori — APPROVED** [review]
lgtm

**Comment by hayatoito** [comment]
Let me merge this.
Thanks for working on this!

**Pull request merged**
