### PR TITLE
Change gen-signedexchange default to b3.

### PR DESCRIPTION
**Pull request by twifkak**

### CODE REVIEW

**Comment by twifkak** [comment]
cc @jeffjose

**Comment by jeffjose** [comment]
Can we update b2 -> b3 here too please? https://github.com/WICG/webpackage/blob/master/examples/firebase.json

**Comment by twifkak** [comment]
@jeffjose Yep, that's in this PR.

**Comment by jeffjose** [comment]
Ah yes, missed it the first time around. Thank you, @twifkak!

**Pull request merged**
